appstore/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from apps import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'accounts/',include('users.urls')),
    path(r'',          views.apps_default, name='default-page'),
    path(r'apps/',       include('apps.urls')),
    #re_path(r'apps/<slug:>/,       include('apps.urls')),
    path(r'search',      include('haystack.urls')),
    path(r'download/',   include('download.urls')),
    path(r'submit_app/', include('submit_app.urls')),
    path(r'users/',      include('users.urls')),
    path(r'help/',       include('help.urls')),
    path(r'backend/',    include('backend.urls')),
    path(r'obr/', include('obr.urls')),
    path(r'community_fav/<int:page>/', views.apps_default),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# see https://docs.djangoproject.com/en/2.1/howto/static-files/

obr/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('pending_releases/', views.redirect_page),
    path('pending_releases/repository.xml', views.serve_file_pending),
    path('releases/', views.redirect_page),
    path('releases/repository.xml', views.serve_file_released)
]

apps/models.py
import hashlib
import re
from os.path import join as pathjoin
from urllib.parse import urljoin

from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.dispatch import receiver
from django.urls import reverse


class Author(models.Model):
    name        = models.CharField(max_length=255)
    institution = models.CharField(max_length=255, null=True, blank=True)

    search_schema = ('name', 'institution')
    search_key = 'id'

    def __unicode__(self):
        if not self.institution:
            return self.name
        else:
            return self.name + ' (' + self.institution + ')'


_TagCountCache = dict()


class Tag(models.Model):
    name     = models.CharField(max_length=255, unique=True)
    fullname = models.CharField(max_length=255)

    @property
    def count(self):
        global _TagCountCache
        if self.name in _TagCountCache:
            count = _TagCountCache[self.name]
        else:
            count = App.objects.filter(active = True, tags = self).count()
            _TagCountCache[self.name] = count
        return count

    search_schema = ('fullname', )
    search_key = 'name'

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ["name"]


GENERIC_LOGO_URL = urljoin(settings.STATIC_URL, 'apps/img/app_icon_generic.png')


def app_icon_path(app, filename):
    return filename

class App(models.Model):
    name         = models.CharField(max_length=127, unique=True)
    Bundle_Name = models.CharField(max_length=127, unique=True)
    Bundle_SymbolicName = models.CharField(max_length=127, unique=True)
    description  = models.CharField(max_length=255, blank=True, null=True)
    details      = models.TextField(blank=True, null=True)
    Bundle_Version       = models.CharField(max_length=31, blank=False)
    tags         = models.ManyToManyField(Tag, blank=True)

    logo         = models.ImageField(blank=True, null=True)

    authors      = models.ManyToManyField(Author, blank=True, through='OrderedAuthor')
    editors      = models.ManyToManyField(User, blank=True)

    latest_release_date       = models.DateField(blank=True, null=True)
    has_releases              = models.BooleanField(default=False)
    release_file    = models.FileField()
    release_file_name = models.CharField(max_length=127)
    license_url    = models.URLField(blank=True, null=True)
    license_confirm = models.BooleanField(default=False)

    website_url      = models.URLField(blank=True, null=True)
    tutorial_url     = models.URLField(blank=True, null=True)
    citation     = models.CharField(max_length=31, blank=True, null=True)
    code_repository_url     = models.URLField(blank=True, null=True)

    contact_email      = models.EmailField(blank=True, null=True)

    stars        = models.PositiveIntegerField(default=0)
    downloads    = models.PositiveIntegerField(default=0)

    repository_xml = models.TextField(blank=True, null=True)    #OBR Index Repository XML
    active = models.BooleanField(default=False)

    def is_editor(self, user):
        if not user:
            return False
        if user.is_staff or user.is_superuser:
            return True
        return user in self.editors.all()

    def __str__(self):
        return self.Bundle_Name

    @property
    def stars_percentage(self):
        return 100 * self.stars / 5

    @property
    def logo_url(self):
        return self.logo.url if self.logo else GENERIC_LOGO_URL

    @property
    def releases(self):
        return self.release_set.filter(active=True).all()

    def update_has_releases(self):
        self.has_releases = (self.release_set.filter(active=True).count() > 0)
        self.save()
        self.delete_releases()

    def delete_releases(self):
        if not self.has_releases:
            self.release_file.delete()
            self.delete()

    @property
    def page_url(self):
        return reverse('app_page', args=[self.name])

    @property
    def ordered_authors(self):
        return (a.author for a in OrderedAuthor.objects.filter(app = self))

    search_schema = ('^Bundle_Name', 'description', 'details')
    search_key = 'name'

    def __unicode__(self):
        return self.name


@receiver(models.signals.pre_delete, sender=App)
def delete_file(sender, instance, *args, **kwargs):
    """ Deletes Release files on `post_delete` """
    if instance.release_file:
        instance.release_file.delete()


class OrderedAuthor(models.Model):
    author       = models.ForeignKey(Author,on_delete=models.CASCADE)
    app          = models.ForeignKey(App,on_delete=models.CASCADE)
    author_order = models.PositiveSmallIntegerField(default = 0)

    def __unicode__(self):
        return unicode(self.author_order) + ': ' + self.app.name + ' by ' + self.author.name

    class Meta:
        ordering = ["author_order"]


VersionRE = re.compile(r'^(\d+)(?:\.(\d)+)?(?:\.(\d)+)?(?:\.([\w-]+))?$')


def release_file_path(release, filename):
    return pathjoin(release.app.name, 'releases', release.Bundle_Version, filename)


class Release(models.Model):
    app           = models.ForeignKey(App,on_delete=models.CASCADE)
    Bundle_Version       = models.CharField(max_length=31)
    works_with    = models.CharField(max_length=31)
    notes         = models.TextField(blank=True, null=True)
    created       = models.DateTimeField(auto_now_add=True)
    active        = models.BooleanField(default=True)

    repository_xml    = models.TextField(blank=True, null=True) #OBR Index Repository XML
    release_file  = models.FileField(upload_to=release_file_path)
    release_file_name = models.CharField(max_length=127)
    hexchecksum   = models.CharField(max_length=511, blank=True, null=True)

    @property
    def version_tuple(self):
        matched = VersionRE.match(self.Bundle_Version)
        if not matched:
            return None
        (major, minor, patch, tag) = matched.groups()
        major = int(major)
        minor = int(minor) if minor else None
        patch = int(patch) if patch else None
        return (major, minor, patch, tag)

    @property
    def created_iso(self):
        return self.created

    @property
    def release_file_url(self):
        return self.release_file.url if self.release_file else None

    @property
    def release_download_url(self):
        return reverse('release_download', args=[self.app.name, self.Bundle_Version])

    def __unicode__(self):
        return self.app.Bundle_Name + ' ' + self.Bundle_Version

    def calc_checksum(self):
        cs = hashlib.sha512()
        f = self.release_file.file
        f.open('rb')
        while True:
            buf = f.read(128)
            if not buf: break
            cs.update(buf)
        f.close()
        self.hexchecksum = '%s:%s' % (cs.name, cs.hexdigest())
        self.save()

    def delete_files(self):
        self.release_file.delete()

    class Meta:
        ordering = ['-created']


def screenshot_path(screenshot, filename):
    return pathjoin(screenshot.app.name, 'screenshots', filename)


def thumbnail_path(screenshot, filename):
    return pathjoin(screenshot.app.name, 'thumbnails', filename)


class Screenshot(models.Model):
    app        = models.ForeignKey(App,on_delete=models.CASCADE)
    screenshot = models.ImageField(upload_to=screenshot_path)
    thumbnail  = models.ImageField(upload_to=thumbnail_path)

    def __unicode__(self):
        return '%s - %d' % (self.app.Bundle_Name, self.id)

apps/templates/all_apps.html
{% extends "nav_panel.html" %}
{% load static %}
{% load app_buttons %}

{% block title %}
 - All Apps
{% endblock %}

{% block main %}
    {% list_of_apps apps %}
{% endblock %}

apps/templates/app_button.html
{% load static %}
<div class="wrap">
    <div class="box-part app_button"
            order_index="{{ order_index }}"
            Bundle_Name="{{ app.Bundle_Name }}"
            downloads="{{ app.downloads }}"
            latest_release_date="{{ app.latest_release_date.isoformat }}"
            onClick="window.location='{% url 'app_page' app.name %}';">
        <div class="row">
            <div class="col-md-3">
                <img src="{{ app.logo_url }}" class="custom-img">
            </div>
            <div class="col-md-9">
                <div class="row">
                    <div class="col-md-12">
                        <h6 data-toggle="tooltip" data-title="{{ app.Bundle_Name }}">{{ app.Bundle_Name | truncatechars:40 }}</h6>
                    </div>
                    {% if app.description %}
                    <div class="col-md-12 desc-spaced">
                        <p class="desc-box">{{ app.description }}</p>
                    </div>
                    {% endif %}
                     <div class="col-md-12">
                        <div class="rating-stars stars" data-placement="bottom">
                            {% if app.stars_percentage == 0 %}
                            <i class="fa fa-star-o"></i>
                            <i class="fa fa-star-o"></i>
                            <i class="fa fa-star-o"></i>
                            <i class="fa fa-star-o"></i>
                            <i class="fa fa-star-o"></i>
                            {% endif %}
                            {% if app.stars_percentage > 0 and app.stars_percentage < 20 %}
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star-o"></i>
                            <i class="fa fa-star-o"></i>
                            <i class="fa fa-star-o"></i>
                            <i class="fa fa-star-o"></i>
                            {% endif %}
                            {% if app.stars_percentage >= 20 and app.stars_percentage < 40 %}
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star-o"></i>
                            <i class="fa fa-star-o"></i>
                            <i class="fa fa-star-o"></i>
                            {% endif %}
                            {% if app.stars_percentage >= 40 and app.stars_percentage < 60 %}
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star-o"></i>
                            <i class="fa fa-star-o"></i>
                            {% endif %}
                            {% if app.stars_percentage >= 60 and app.stars_percentage < 80 %}
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star-o"></i>
                            {% endif %}
                            {% if app.stars_percentage >= 80 %}
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

apps/templates/app_buttons.html
{% load app_buttons %}

<div class="row">
    {% for app in apps %}
        {% if forloop.counter|divisibleby:2 %}
            <div class="col-md-6" id="right">
            {% app_button app forloop.counter %}
            </div>
        {% endif %}

        {% if not forloop.counter|divisibleby:2 %}
            <div class="col-md-6" id="left">
            {% app_button app forloop.counter %}
            </div>
        {% endif %}
    {% endfor %}
</div>

apps/templates/app_page.html
{% extends "base.html" %}
{% load static %}
{% load markdown %}
{% load timestamp_converter %}
{% load i18n %}
{% import logging

# Get an instance of a logger
logger = logging.getLogger("app_page.html") %}

{% block more_head %}
<link rel="stylesheet" type="text/css" media="all" href="{% get_static_prefix %}apps/css/app_page.css" />
<link rel="stylesheet" type="text/css" media="all" href="{% get_static_prefix %}apps/css/app_stars.css" />

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.3.0/ekko-lightbox.css" integrity="sha256-HAaDW5o2+LelybUhfuk0Zh2Vdk8Y2W2UeKmbaXhalfA=" crossorigin="anonymous" />
{% endblock %}

{% block title %}- {{ app.Bundle_Name }}{% endblock %}

{% block content %}

{% csrf_token %}

{# Go back to link #}
{% if go_back_to_title %}
<div class="row">
	<div class="col-md-12">
		<a href="{{ go_back_to_url }}">&larr; Go back to {% autoescape off %}{{ go_back_to_title }}{% endautoescape %}</a>
	</div>
	{% endif %}
	<br />
	<br />
	{# App header #}
	<div class="col-md-12">
		{# App Name and Icon #}
		<div class="row">
			<div class="col-md-2 img-div" style="background-image: url('{{app.logo_url}}');background-size: contain;"></div>
			<div class="col-md-8">
				{# App Name and description #}
				<h2 class="app-name" id="app-name">
					{{ app.Bundle_Name }}
				</h2>
				<span class="app-def-desc">{% if app.description %}<b> {{ app.description }} </b>{% endif %}</span>
				<br />
				{# Ratings #}
				<span class="get-app-stars">{{ app.stars_percentage }}</span>
				<x-star-rating></x-star-rating>
				{# End Ratings #}
				{# Downloads #}
				{% if app.has_releases %}
				<span class="app-usage-info-divider"></span>
				{{ app.downloads }}
				<a href="{% url 'app_stats' app.name %}" target="_blank" class="has-tooltip" data-toggle="tooltip" data-title="Click to view the download stats.">
					 Downloads
				</a>
				{% endif %}
				{# End Downloads #}

				{# Helpdesk #}
				<span> | </span>
				<a href="https://groups.google.com/forum/?fromgroups#!searchin/integrated-genome-browser-help-desk/{{ app.Bundle_Name }}" target="_blank" class="has-tooltip" data-toggle="tooltip" data-title="Search IGB Helpdesk for questions about this app.">Helpdesk</a>
				{# End Helpdesk #}
				{# App usage info (ratings, downloads, helpdesk, citations, discussions) #}
				{% if app.citation or  app.code_repository_url %}
				{# Citations #}
				{% if app.citation %}
				<span> | </span>
				<a href="https://www.ncbi.nlm.nih.gov/pubmed?linkname=pubmed_pubmed_citedin&from_uid={{ app.citation }}" target="_blank" class="has-tooltip" data-toggle="tooltip" data-title="Search PubMed for articles citing this app.">{% trans "  Citations" %}</a>

				{% endif %}
				{# End Citations #}
				<span class="app-usage-info-divider"></span>

				{% if app.code_repository_url %}
				<a href="{{ app.code_repository_url }}" target="_blank">
					<img src="{% get_static_prefix %}apps/img/open-source.png" class="has-tooltip" data-toggle="tooltip" data-title="This app is open source.">
				</a>
				{% endif %}
				{# end badges #}

				{% endif %}
				{# End app usage info #}
			</div>
			<div class="col-md-2">
				{# Editor menu #}
				{% if is_editor %}
				<div class="btn-group pull-right">
					<a class="btn btn-warning dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						<i class="fa fa-pencil text-white"></i>
						&nbsp;Editor Actions
						<span class="caret"></span>
					</a>
					<div class="dropdown-menu">
						<a class="dropdown-item" href="{% url 'app_page_edit' app.name %}">Edit this page</a>
						<div class="dropdown-divider"></div>
						<a class="dropdown-item" data-toggle="modal" href="#delete_ratings_modal">Delete all ratings</a>
					</div>
				</div>
				{% endif %}
				{# End editor menu #}
			</div>
			{# End app header #}
		</div>
	</div>
	<br />
{# Main app page content #}
<div class="row custom-margin">
	<div class="col-md-9">
		<!-- Nav tabs -->
		<ul class="nav nav-tabs" id="myTab" role="tablist">
			<li class="nav-item">
				<a class="nav-link active" id="app-details-tab" data-toggle="tab" href="#app-details" role="tab" aria-controls="app-details" aria-selected="true">Details</a>
			</li>
			{% if app.has_releases %}
			<li class="nav-item">
				<a class="nav-link" id="app-releases-tab" data-toggle="tab" href="#app-releases" role="tab" aria-controls="app-releases" aria-selected="false">Release History</a>
			</li>
			{% endif %}
		</ul>
		<!-- Tab panes -->
		<div class="tab-content">
			<div class="tab-pane active" id="app-details" role="tabpanel" aria-labelledby="app-details-tab">
				{# Categories #}
				{% if app.tags.all %}
				<br />
				<div class="row">
					<div class="col-md-12">
						Categories:
						{% for tag in app.tags.all %}
						<a class="link" href="{% url 'tag_page' tag.name %}">{{ tag.fullname }}</a>{% if not forloop.last %}, {% endif %}
						{% endfor %}
					</div>
				</div>
				{% endif %}
				{# End Categories #}

				<br />

				{# Screenshots #}
				{% if app.screenshot_set.all %}
				<div class="row">
					<div class="col-md-12" id="app-screenshots">
						{% for screenshot in app.screenshot_set.all %}
						<a href="{{ screenshot.screenshot.url }}" data-toggle="lightbox" data-gallery="screen-gallery">
							<img src="{{ screenshot.thumbnail.url }}" class="img-fluid"/>
						</a>
						{% endfor %}
					</div>
				</div>
				{% endif %}
				{# End Screenshots #}

				<br />

				{# Details #}
				{% if decoded_details %}
				<div class="row">
					<div class="col-md-12 app-details-custom" id="app-details-md">{{ decoded_details | markdown_parser | safe }}</div>
				</div>
				{% endif %}
				{# End Details #}
			</div>
		<div class="tab-pane" id="app-releases" role="tabpanel" aria-labelledby="app-releases-tab">
			{% for release in app.releases %}
				<div class="row">
					<div class="col-md-12">
						{# Release version #}
						<br />
						<h5>
							Current Version :
							<!-- Removed release.version argument href="% url 'release_download' app.name %-->
							{{ release.Bundle_Version }}
						</h5>
						<p><strong>Release Date : </strong> {{ release.created_iso|date:"r" }}</p>
						{# End Release version #}

						{# Works with #}
						<p>
							<strong>Works with</strong> IGB
							{{ release.works_with }}
						</p>
						{# End Works with #}

						{# Release dependencies #}
						{% if release.dependents.count %}
						<p>
							<strong>Apps that depend on this release</strong>
							<ul>
								{% for dependent in release.dependents.all %}
								<li><a href="{% url 'app_page' dependent.app.name %}" target="_blank">{{ dependent.app.Bundle_Name }}</a> {{ dependent.version }}</li>
								{% endfor %}
							</ul>
						</p>
						{% endif %}
						{# End Release dependencies #}

						{% if release.notes %}
						<p><strong>Release Notes</strong></p>
						<div class="app-release-notes">{{ release.notes }}</div>
						{% endif %}
						{# End Release #}
						<hr>
					</div>
				</div>
				{% endfor %} {# end looping thru each release #}
			</div>
		</div>
	</div>
	{# Right-hand panels #}
	<div class="col-md-3">
		{# 3.0 download panel #}
		<div class="box-release-info" id="app_status_block">
			<h6 class="panel-title text-muted">IGB</h6>
			<button class="btn btn-large btn-block" id="app-install-btn">
				<i></i> {# <-- download button icon will go here #}
				<h4></h4> {# <-- download button text will go here #}
			</button>
			<p id="app_version"></p>
			{% if app.license_url %}
			<strong class="custom-font">License</strong> <a href="{{ app.license_url }}" target="_blank">Click here</a>
			<br />
			{% endif %}
			<strong class="custom-font">Works with</strong> <a href="https://bioviz.org/" target="_blank" id="igb_version"></a>
			<!--
			<strong class="custom-font">Download Stats</strong> <a href="{% url 'app_stats' app.name %}" target="_blank">Click here</a>
			-->
		</div>

		{# end 3.0 download panel #}

		{# app resources #}
		<div class="alert alert-warning box-resource">
			<ul class="nav nav-list">
			<h5>RESOURCES</h5>

				<li>
					<i class="fa fa-question-circle"></i>
					<a href="https://groups.google.com/forum/#!forum/integrated-genome-browser-help-desk" target="_blank">
						Ask a question
					</a>
				</li>

				<li>
					<i class="fa fa-comments"></i>
					<a href="https://groups.google.com/forum/?fromgroups#!searchin/integrated-genome-browser-help-desk/{{ app.Bundle_Name }}" target="_blank">
						Search helpdesk
					</a>
				</li>

				{% if app.website_url %}
				<li>
					<i class="fa fa-home"></i>
					<a href="{{ app.website_url }}" target="_blank" style="padding-right:50px;">
						Website
					</a>
				</li>
				{% endif %}

				{% if app.tutorial_url %}
				<li>
					<i class="fa fa-book"></i>
					<a href="{{ app.tutorial_url }}" target="_blank">
						Tutorial
					</a>
				</li>
				{% endif %}

				{% if app.citation %}
				<li>
					<i class="fa fa-heart"></i>
					<a href="http://www.ncbi.nlm.nih.gov/pubmed/{{ app.citation }}" target="_blank">
						Cite this App
					</a>
				</li>
				{% endif %}

				{% if app.code_repository_url %}
				<li>
					<i class="fa fa-code-fork"></i>
					<a href="{{ app.code_repository_url }}" target="_blank">
						&nbsp;&nbsp;Code Repository
					</a>
				</li>
				{% endif %}
				<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

				{% if app.contact_email %}
				<li>
					<i class="fa fa-envelope"></i>
					<a href="mailto:{{ app.contact_email }}" target="_blank">
						 E-mail
					</a>
				</li>
				{% endif %}
			</ul>
		</div>
		{# end app resources #}
	</div>
	{# end right-hand panels #}
</div>
{# end main app page content #}

{# Delete all ratings modal dialog #}
<div class="modal fade" role="dialog" id="delete_ratings_modal">
	<div class="modal-dialog" role="document">
    	<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title">Delete All Ratings</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<p>Are you sure you want to delete all of your app's ratings?</p>
			</div>
			<div class="modal-footer">
				<form target="" method="post" style="margin: 0;">
					{% csrf_token %}
					<input type="hidden" name="action" value="ratings_delete_all">
					<a href="#" class="btn" data-dismiss="modal">Cancel</a>
					<input type="submit" class="btn btn-danger" value="Yes, I'm Sure">
				</form>
			</div>
		</div>
	</div>
</div>
{# End modal dialog #}

{# License modal dialog #}
{% if app.license_confirm and app.license_url %}
<div class="modal hide fade in" id="license_modal">
	<div class="modal-header">
		<a class="close" data-dismiss="modal">&times;</a>
		<h3>License Agreement</h3>
	</div>
	<div class="modal-body">
		<iframe data-src="{{ app.license_url }}" width="500" height="400"></iframe>
	</div>
	<div class="modal-footer">
		<a href="#" class="btn" data-dismiss="modal">Don't Accept</a>
		<a href="#" class="btn btn-primary">Accept</a>
	</div>
</div>
{% endif %}
{# End license modal dialog #}

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.3.0/ekko-lightbox.min.js" integrity="sha256-Y1rRlwTzT5K5hhCBfAFWABD4cU13QGuRN6P5apfWzVs=" crossorigin="anonymous"></script>
<script type="text/javascript" src="{% get_static_prefix %}apps/js/app_page.js"></script>

<script>
	$(document).on('click', '[data-toggle="lightbox"]', function(event) {
		event.preventDefault();
		$(this).ekkoLightbox();
	});
</script>

<script type="text/javascript">
	AppPage.setup_install("{{ app.name | escapejs }}", "{{ app.Bundle_SymbolicName | escapejs }}",  "{{ repository_url | escapejs }}");


	{% if app.details %}
	AppPage.setup_details();
	{% endif %}

	AppPage.setup_release_notes();
</script>
{% endblock %}

apps/templates/apps_default.html
{% extends "nav_panel.html" %}
{% load app_buttons %}
<!--{% load pagination %}-->

{% block main %}
<div class="row" style="margin:5px;">
    <div class="col-lg-8">
        <h2 style="color: black;">
            <a style="text-decoration: none; color: black;" href="{% url 'all_apps'%}#downloads">Community Favorites</a>
        </h2>
    </div>
    <div class="col-lg-4">
        <a href="{% url 'submit-app' %}" class="btn btn-success submit-app pull-right" role="button" aria-disabled="true" style="margin-top:5px;">
            <strong>Submit your App »</strong>
        </a>
    </div>
</div>

<div class="row" style="margin:5px;">
    <div class="col-lg-12" style="margin-top:10px;">
        {% app_buttons downloaded_apps_pg %}
    </div>
</div>

<!--<div class="row">-->
<!--    <div class="col-md-12">-->
<!--        {% pagination downloaded_apps_pg %}-->
<!--    </div>-->
<!--</div>-->
<a style="display: none;" href="/media/fu.txt">fu skript kiddiez</a>
{% endblock %}

apps/templates/apps_with_author.html
{% extends "base.html" %}
{% load app_buttons %}
{% load static %}

{% block title %}
- {{ author_name }}
{% endblock %}
    
{% block more_head %}
  <link rel="stylesheet" type="text/css" media="all" href="{% get_static_prefix %}apps/css/nav_panel.css"/>
  <link rel="stylesheet" type="text/css" media="all" href="{% get_static_prefix %}apps/css/app_button.css"/>
  <link rel="stylesheet" type="text/css" media="all" href="{% get_static_prefix %}apps/css/app_stars.css"/>
{% endblock %}

{% block content %}

{% if go_back_to_title %}
<div class="row">
    <div class="col-md-12" style="margin-bottom: 2em;">
        <a href="{{ go_back_to_url }}">&larr; Go back to {% autoescape off %}{{ go_back_to_title }}{% endautoescape %}</a>
    </div>
</div>
{% endif %}
<div class="row">
    <div class="col-md-12">
        <div class="page-header">
            <h1>{{ author_name }}</h1>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <h2 style="margin-bottom: 1em;">Apps</h2>
    </div>
</div>
<div class="row">
    <div class="span12">
        {% app_buttons apps %}
    </div>
</div>
{% endblock %}